 -- phase-1 exploratory analysis queries

-- 1.1 total revenue generated by food delivery app
SELECT SUM(order_amount - discount) AS total_revenue
FROM orders;


-- 1.2 Total order per city
SELECT r.city, COUNT(*) AS total_orders
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.city
ORDER BY total_orders DESC;

-- 1.3 Top 10 customers by spending
SELECT c.customer_id, c.name, SUM(o.order_amount - o.discount) AS total_spent
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.name
ORDER BY total_spent DESC
LIMIT 10;

-- PHASE 2 — CUSTOMER SEGMENTATION 

-- 2.1 Customer Category (Gold/Silver/Bronze)
SELECT customer_id, name,
CASE 
    WHEN total_spent >= 10000 THEN 'Gold'
    WHEN total_spent BETWEEN 5000 AND 9999 THEN 'Silver'
    ELSE 'Bronze'
END AS customer_category
FROM (
    SELECT c.customer_id, c.name, SUM(o.order_amount - o.discount) AS total_spent
    FROM customers c
    LEFT JOIN orders o ON c.customer_id = o.customer_id
    GROUP BY c.customer_id, c.name
) t
ORDER BY total_spent DESC;

-- PHASE 3 — RESTAURANT PERFORMANCE 
-- 3.1 Top 10 Restaurants by Revenue 
SELECT r.restaurant_id, r.restaurant_name, r.city,
       SUM(o.order_amount - o.discount) AS total_revenue
FROM restaurants r
JOIN orders o ON r.restaurant_id = o.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name, r.city
ORDER BY total_revenue DESC
LIMIT 10;

-- 3.2 Average Rating vs Revenue

SELECT 
    r.restaurant_id,
    r.restaurant_name,r.rating,
    SUM(o.order_amount - o.discount) AS total_revenue
FROM restaurants r
LEFT JOIN orders o 
    ON r.restaurant_id = o.restaurant_id
GROUP BY 
    r.restaurant_id, r.restaurant_name, r.rating
ORDER BY 
    r.rating DESC;
       

-- PHASE 4 — DELIVERY ANALYSIS
-- 4.1 Average Delivery Time Per City
SELECT r.city, AVG(o.delivery_time_min) AS avg_delivery_time
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.city
ORDER BY avg_delivery_time DESC;

-- 4.2 Late Deliveries (Above 45 Minutes)
SELECT r.city,r.restaurant_name,
       COUNT(*) AS late_deliveries
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
WHERE delivery_time_min > 45
GROUP BY r.city, r.restaurant_name
ORDER BY late_deliveries DESC;


-- PHASE 5 — PAYMENT & DISCOUNT ANALYSIS
-- 5.1 Payment Method Distribution
SELECT payment_method,
       COUNT(*) AS count
FROM orders
GROUP BY payment_method
ORDER BY count DESC;

-- 5.2 Discount Impact on Revenue
SELECT 
    SUM(order_amount) AS gross_revenue,
    SUM(discount) AS total_discount,
    SUM(order_amount - discount) AS net_revenue,
    (SUM(order_amount - discount) * 100.0 / SUM(order_amount)) AS revenue_percentage_after_discount
FROM orders;

 
 -- PHASE 6 — ADVANCED SQL 

 -- 6.1.Monthly Revenue Using CTE 
 WITH monthly_revenue AS (
  SELECT MONTH(order_date) AS month,
        (SUM(order_amount - discount)) AS revenue
  FROM orders
  GROUP BY month
)

SELECT month, revenue
FROM monthly_revenue
ORDER BY month;

-- 6.2.Rank Restaurants by Revenue (Window Function) 

SELECT r.restaurant_id,
    r.restaurant_name,
    SUM(o.order_amount - o.discount) AS total_revenue,
    RANK() OVER (ORDER BY SUM(o.order_amount - o.discount) DESC) AS revenue_rank
FROM restaurants r
JOIN orders o ON r.restaurant_id = o.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name
ORDER BY total_revenue DESC;


-- 6.3.Above Average Revenue Restaurants (Subquery)
SELECT r.restaurant_id,
    r.restaurant_name,
    SUM(o.order_amount - o.discount) AS total_revenue
FROM restaurants r
JOIN orders o 
    ON r.restaurant_id = o.restaurant_id
GROUP BY 
    r.restaurant_id, 
    r.restaurant_name
HAVING 
    SUM(o.order_amount - o.discount) > (
        SELECT AVG(total_rev)
        FROM (SELECT SUM(order_amount - discount) AS total_rev
             FROM orders
             GROUP BY restaurant_id
             ) AS revenue_table)
ORDER BY total_revenue DESC;

-- PHASE 7 — DATABASE OBJECTS 

--7.1.Create Revenue View 
CREATE VIEW Revenue_view AS
SELECT r.restaurant_id,
    r.restaurant_name,
    SUM(o.order_amount - o.discount) AS total_revenue 
FROM restaurants r
JOIN orders o ON r.restaurant_id = o.restaurant_id  
GROUP BY r.restaurant_id, r.restaurant_name;


-- 7.2.Stored Procedure: Get Top N Restaurant
CREATE PROCEDURE GetTopNRestaurants(IN top_n INT)
BEGIN 
    SET @LIMIT_val = top_n;
    set @sql_query = CONCAT(
        'SELECT 
             restaurant_id, restaurant_name, total_revenue 
         FROM Revenue_view 
         ORDER BY total_revenue DESC 
         LIMIT ', @LIMIT_val);
    PREPARE stmt FROM @sql_query;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END;

call GetTopNRestaurants(5);




